### ISSUE TITLE
error 500 when trying to initialize the doc.page with a repository name that contains a dot

### ISSUE THREAD

**Issue by vincenzopalazzo** [invertase/docs.page#160] opened 2022-04-09 09:30 UTC
I'm sure that there is an error from my side but I don't know what it is, because I'm not able to see the exception anywhere.

I'm trying to build the doc for https://github.com/vincenzopalazzo/changelog.dart and I configured the repository as the doc suggested. However, I receive the following error https://docs.page/vincenzopalazzo/changelog.dart

Any idea?

**Comment by rydmike** [comment] 2022-04-09 12:23
Interesting, could the cause be that your repo has "dot" in the name be the cause? Setup looked OK to me, just working on docs.page setup too.  So I just came here to check open issues to be aware of and saw your question. Maybe test with another dummy repo without "." in the repo name, just to test the theory.

My docs.page is still a work in progress: https://docs.page/rydmike/flex_color_scheme_docs (repo https://github.com/rydmike/flex_color_scheme_docs) but never saw any issue like that.

I must say I really like docs.page, so simple to work with. Sure not a super lot of features, but I don't really need more for a documentation site. I would not even mind using this for personal totally clutter and ad free tech/code blog :)

**Comment by vincenzopalazzo** [comment] 2022-04-09 13:58
Yes! reproduced https://docs.page/vincenzopalazzo/cpstl

I think that the problem is the . in the name

**Comment by cabljac** [comment] 2022-04-09 14:45
Hey! thanks for reporting this - looking into it now. We've recently switched to remix and it could be the `.` isn't being handled correctly in the routes.

**Comment by vincenzopalazzo** [comment] 2022-04-09 14:56
>Hey! thanks for reporting this - looking into it now. We've recently switched to remix and it could be the . isn't being handled correctly in the routes.

Yeah, sorry but I love the dot convention in the name :)

**Comment by cabljac** [comment] 2022-04-09 15:10
ah i think I found the issue -

in your frontmatter you need to put the description in double quotes -

```
description: "changelog.dart: a collection of tools to manages in a fashion way a repository as maintainer."
```

**Comment by cabljac** [comment] 2022-04-09 15:15
> I must say I really like docs.page, so simple to work with. Sure not a super lot of features, but I don't really need more for a documentation site. I would not even mind using this for personal totally clutter and ad free tech/code blog :)

Thanks! Any suggestions for features you might like?

**Comment by cabljac** [comment] 2022-04-09 20:38
Going to close this as it seems it's working for you :) feel free to reopen if it still has issues.

**Closed by cabljac** 2022-04-09 20:38 UTC
